trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  scriptPath: 'infra/azcli/script.sh'
  artifactName: 'deployment-scripts'
  serviceConnection: 'arm-svc-con' 
  environment: 'dev'

stages:

# Stage 1 - Publish the script
- stage: PublishScript
  displayName: 'Publish Deployment Script'
  jobs:
  - job: Publish
    displayName: 'Publish Script as Artifact'
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(scriptPath)'
        artifact: '$(artifactName)'
        publishLocation: 'pipeline'

# Stage 2 - Download & Run the Script
- stage: Deploy
  displayName: 'Deploy Azure Resources'
  dependsOn: PublishScript
  jobs:
    - deployment: DeployInfraResources
      displayName: "Deploy Resources for: $(environment)"
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: $(artifactName)

              - task: AzureCLI@2
                displayName: 'Run Deployment Script'
                inputs:
                  azureSubscription: '$(serviceConnection)'
                  scriptType: bash
                  scriptLocation: scriptPath
                  scriptPath: '$(Pipeline.Workspace)/$(artifactName)/script.sh'

              # - task: Bash@3
              #   inputs:
              #     filePath: './script.sh'
              #     workingDirectory: $(Pipeline.Workspace)/$(artifactName)
              #     displayName: 'Run script.sh'

              - script: |
                  echo "Starting the deployment"
                  .$(Pipeline.Workspace)/$(artifactName)/script.sh
                displayName: 'Run deploy.sh directly'
