# name: 1.0.$(BuildID)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Publish
    displayName: "Publish Artifact"
    jobs:
      - job:
        steps:
          - task: CopyFiles@2
            displayName: Infra Files to Build Artifacts
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)/infra"
              Contents: |
                /**
              TargetFolder: "$(Build.ArtifactStagingDirectory)/infra"

          - publish: $(Build.ArtifactStagingDirectory)
            displayName: Publish Transformed artifacts
            artifact: InfraPackage

  - stage: Dev
    displayName: "Dev"
    jobs:
      - deployment: DeployInfraResources
        displayName: "Deploy Resources for: ${{parameters.environment}} environment"
        environment: "${{parameters.environment}}"
        strategy:
          runOnce:
            deploy:
              steps:                
                - task: AzureCLI@2
                  displayName: "Deploy Infra" 
                  inputs:
                    azureSubscription: "${{parameters.serviceconnection}}"
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    workingDirectory: $(Pipeline.Workspace)
                    inlineScript: |
                      $filename = "$(Pipeline.Workspace)/InfraPackage/infra/azcli/script.sh"
                                  
                      Write-Host "STARTING DEPLOYMENT......."

                      ./$filename 
                  
                      Write-Output "Successfully validate"