# name: 1.0.$(BuildID)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'arm-svc-con'
  environment: 'dev'

stages:
  - stage: Publish
    displayName: "Publish Artifact"
    jobs:
      - job:
        steps:
          - task: CopyFiles@2
            displayName: Infra Files to Build Artifacts
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)/infra"
              Contents: |
                /**
              TargetFolder: "$(Build.ArtifactStagingDirectory)/infra"

          - publish: $(Build.ArtifactStagingDirectory)
            displayName: Publish Transformed artifacts
            artifact: InfraPackage

  - stage: Dev
    displayName: "Dev"
    jobs:
      - deployment: DeployInfraResources
        displayName: "Deploy Resources for: $(environment)"
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:    
                - script: |

                    echo "Working Directory: $(System.DefaultWorkingDirectory)"
                    ls -la "$(System.DefaultWorkingDirectory)"

                    echo "Working Directory: $(Build.sourcesdirectory)"
                    ls -la "$(Build.sourcesdirectory)"

                    echo "Working Directory: $(Build.ArtifactStagingDirectory)"
                    ls -la "$(Build.ArtifactStagingDirectoryy)"

                    echo "Working Directory: $(Pipeline.Workspace)"
                    ls -la "$(Pipeline.Workspace)"




                    echo "Starting the deployment"
                    .$(Build.ArtifactStagingDirectory)/infra/azcli/script.sh
                  displayName: 'Run deploy.sh directly'

                # - task: AzureCLI@2
                #   displayName: "Deploy Infra" 
                #   inputs:
                #     azureSubscription: $(serviceConnection)
                #     scriptType: 'pscore'
                #     scriptLocation: 'inlineScript'
                #     workingDirectory: $(Pipeline.Workspace)
                #     inlineScript: |
                #       $filename = "$(Pipeline.Workspace)/InfraPackage/infra/azcli/script.sh"
                                  
                #       Write-Host "STARTING DEPLOYMENT......."

                #       ./$(Pipeline.Workspace)/InfraPackage/infra/azcli/script.sh
                  
                #       Write-Output "Successfully validate"