trigger: none

variables:
  serviceConnection: 'arm-svc-con'
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  namespace: 'default'
  imageName: 'order'
  tag: $(Build.BuildId)
  #tag: latest

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and publish stage
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build Publish Docker Images
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker
            inputs:
              dockerVersion: '17.09.0-ce'

          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: 'acr-svc-connection'
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/order-service/Dockerfile'
              tag: $(tag)       

          # # Task 2 publish build artifacts
          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     PathtoPublish: '$(System.DefaultWorkingDirectory)/manifests/order'
          #     ArtifactName: 'order-manifests'
          #     publishLocation: 'Container'